steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-u', 'cloud.google.com/go/logging', 'google.golang.org/api/option']
  env: ['PROJECT_ROOT=app']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'app']
  env: ['PROJECT_ROOT=app']
- name: 'ubuntu'
  args: ['chmod', '+x', 'app']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/makz-labs/go-gcp-logging', '.' ]
images:
- 'gcr.io/$PROJECT_ID/makz-labs/go-gcp-logging'
artifacts:
  objects:
    location: 'gs://makz-support-labs-artifacts/go-gcp-logging'
    paths: ['app']