steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-u', 'cloud.google.com/go/logging', 'google.golang.org/api/option']
  env: ['PROJECT_ROOT=app']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'app']
  env: ['PROJECT_ROOT=app']
- name: 'ubuntu'
  args: ['chmod', '+x', 'app']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/${_REPO_PREFIX}/${_APPLICATION}', '.' ]
images:
- 'gcr.io/${_PROJECT_ID}/${_REPO_PREFIX}/${_APPLICATION}'
substitutions:
    _APPLICATION: $APPLICATION
    _REPO_PREFIX: $REPRO_PREFIX
    _PROJECT_ID: $PROJECT_ID
artifacts:
  objects:
    location: 'gs://${_REPO_PREFIX}/${_APPLICATION}'
    paths: ['app']