steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['get', '-u', 'cloud.google.com/go/logging']
  env: ['PROJECT_ROOT=app']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'app']
  env: ['PROJECT_ROOT=app']
artifacts:
  objects:
    location: 'gs://makz-support-labs-artifacts/${PWD##*/}'
    paths: ['app-${PWD##*/}']